### ISSUE TITLE
Caused by: java.lang.NullPointerException: serviceName

### ISSUE THREAD

**Issue by StarpTech** [paolochiodi/zipkin-simple#8]
Do you have any idea? I run the same code months ago and it had worked.

```
zipkin          |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
zipkin          |       at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
zipkin          | Caused by: java.lang.NullPointerException: serviceName
zipkin          |       at zipkin.internal.Util.checkNotNull(Util.java:60) ~[zipkin-1.26.2.jar!/:na]
zipkin          |       at zipkin.Endpoint.<init>(Endpoint.java:101) ~[zipkin-1.26.2.jar!/:na]
zipkin          |       at zipkin.Endpoint$Builder.build(Endpoint.java:254) ~[zipkin-1.26.2.jar!/:na]
zipkin          |       at zipkin.internal.JsonCodec$1.fromJson(JsonCodec.java:83) ~[zipkin-1.26.2.jar!/:na]
zipkin          |       at zipkin.internal.JsonCodec$1.fromJson(JsonCodec.java:65) ~[zipkin-1.26.2.jar!/:na]
zipkin          |       at zipkin.internal.JsonCodec$2.fromJson(JsonCodec.java:138) ~[zipkin-1.26.2.jar!/:na]
zipkin          |       at zipkin.internal.JsonCodec$2.fromJson(JsonCodec.java:126) ~[zipkin-1.26.2.jar!/:na]
zipkin          |       at zipkin.internal.JsonCodec$4.fromJson(JsonCodec.java:353) ~[zipkin-1.26.2.jar!/:na]
zipkin          |       at zipkin.internal.JsonCodec$4.fromJson(JsonCodec.java:327) ~[zipkin-1.26.2.jar!/:na]
zipkin          |       at zipkin.internal.JsonCodec.readList(JsonCodec.java:629) ~[zipkin-1.26.2.jar!/:na]zipkin          |       ... 69 common frames omitted
zipkin          |
```

**Comment by paolochiodi** [comment]
Can you provide some sample code on the nodejs side that's causing this?

**Comment by StarpTech** [comment]
Here is a list of all called method with the annotationData
```
sendClientSend
     {
      "name": "cmd:add,topic:math"
    }

sendServerRecv
    {
      "service": "math",
      "name": "cmd:add,topic:math"
    }

sendServerSend
    {
      "service": "math",
      "name": "cmd:add,topic:math"
    }

sendClientRecv
    {
      "name": "cmd:add,topic:math"
    }
```

**Comment by StarpTech** [comment]
Hi @paolochiodi thanks for your feedback but I've found the issue.

**Comment by StarpTech** [comment]
Wasn't related to zipkin-simple
